config/core.entity_view_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_page.teaser.yml
config/core.entity_view_display.node.sa_post.default.yml
config/core.entity_view_display.node.sa_post.teaser.yml
config/field.field.node.sa_page.sa_components.yml
config/field.field.node.sa_post.sa_related_posts.yml

Teasers display were updated for the Page and Post CTs

Teasers display were updated for the Page and Post CTs

---

config/core.entity_view_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_post.full.yml
config/core.entity_view_display.node.sa_post.teaser.yml
recipe.yml

Updates post related to card grid and updates adds field group pattern for cards display

updates page and posts displays

---

config/core.entity_form_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_page.default.yml

Set title to H1
Sets all components as collapsed on edit mode

Updates display of page

---

config/field.field.node.sa_page.sa_seo_image.yml
config/field.field.node.sa_post.sa_seo_image.yml

Sets SEO media to use base image style

fixes media display for seo image

---

config/core.entity_view_display.node.sa_post.teaser.yml

Updates Post teaser to simple card pattern

---

config/field.field.node.sa_page.sa_components.yml

Disables Existing Content Paragraph on the node page content type.  Should only available in columns
https://kanopi.teamwork.com/app/tasks/29568641
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc. This should also include work that needs to be 
accomplished post-launch like enabling a plugin._

excludes existing card type from page

---

config/core.entity_form_display.node.sa_page.default.yml

updates form node display to use preview

---

config/core.entity_view_display.node.sa_page.teaser.yml
config/core.entity_view_display.node.sa_post.teaser.yml

Teaserupdate

---

config/core.entity_form_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_page.hero.yml
config/core.entity_view_display.node.sa_page.teaser.yml
config/field.field.node.sa_page.sa_featured_media.yml
config/field.field.node.sa_page.sa_include_mute_button.yml
config/field.field.node.sa_page.sa_include_pause_button.yml

Teamwork Ticket(s): [Change Featured Image to Featured Media](https://kanopi.teamwork.com/app/tasks/29614418)
> Style Page Header Featured Media
* Page CT has Featured Media field instead of Featured Image which accepts Image, Video and Remote Video
* Page CT has options to add a Pause button and Mute button
* Post CT still has Featured Image field
1. Add/edit a Page node
2. Add media to the Featured Media field
3. Select if you want a Pause or Mute button to show (won't show for image)
4. Save and confirm that everything works as expected

Add Field config for Featured Media

---

config/core.entity_form_display.node.sa_page.default.yml

Teamwork Ticket(s): [Change Featured Image to Featured Media](https://kanopi.teamwork.com/app/tasks/29614418)
> Allow Featured Media to have edit button on the edit node screen
1. Create a Hero component or Hero field on the Page CT
2. Confirm for the Featured Media field, you can edit the media after it's been added

Edit Button for Featured Media field

---

recipe.yml

Adds entity_form

---

composer.json

Updates Scheduler content moderation integration

---

config/node.type.sa_page.yml
config/node.type.sa_post.yml

Config Validation

---

recipe.yml

Removes environment indicator ribbon permission

---

recipe.yml

Adds config strict

---

recipe.yml

Updates Content editor

---

config/core.entity_form_display.node.sa_page.default.yml
config/core.entity_form_display.node.sa_post.default.yml
config/core.entity_view_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_page.hero.yml
config/core.entity_view_display.node.sa_page.teaser.yml
config/core.entity_view_display.node.sa_post.default.yml
config/core.entity_view_display.node.sa_post.full.yml
config/core.entity_view_display.node.sa_post.hero.yml
config/core.entity_view_display.node.sa_post.teaser.yml
config/field.field.node.sa_page.field_overlay_invert.yml
config/field.field.node.sa_post.field_overlay_invert.yml

Teamwork Ticket(s): [Change Page and Post to use Hero component](https://kanopi.teamwork.com/app/tasks/29774440)
> Adds the Hero SDC to Page and Post hero
* User can add a Featured Media/Image 
* Hero displays as a SDC
1. Add/edit a Page or Post node
2. Add a Featured Media/Image
3. Set any Hero Options (overlay, header position etc)
4. Save and confirm that the Hero renders as expected

TW29774440 Add Hero SDC to Post and Page Hero

---

composer.json

Updates composer to require v2 packages for saplings.

updates composer to v2 version

---

config/core.entity_form_display.node.sa_page.default.yml
config/core.entity_form_display.node.sa_post.default.yml
config/core.entity_view_display.node.sa_page.default.yml
config/core.entity_view_display.node.sa_page.hero.yml
config/core.entity_view_display.node.sa_page.teaser.yml
config/core.entity_view_display.node.sa_post.default.yml
config/core.entity_view_display.node.sa_post.full.yml
config/core.entity_view_display.node.sa_post.hero.yml
config/core.entity_view_display.node.sa_post.teaser.yml
config/field.field.node.sa_page.sa_components.yml
config/field.field.node.sa_page.sa_overlay_opacity.yml
config/field.field.node.sa_post.sa_overlay_opacity.yml

Updates hero fields to use native bootstrap utiltiies
[link_to_relevant_multidev_or_test_site](insert_link_here)
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc. This should also include work that needs to be 
accomplished post-launch like enabling a plugin._

adds updates for hero display

---

composer.json
config/core.date_format.month_and_year.yml
config/core.entity_view_display.node.sa_page.hero.yml
config/core.entity_view_display.node.sa_page.teaser.yml
config/core.entity_view_display.node.sa_post.hero.yml
config/core.entity_view_display.node.sa_post.teaser.yml
config/views.view.sa_posts.yml
recipe.yml

updates hero displays to use hero component and adds views bootstrap

updates hero displays to use hero component and adds views bootstrap
